apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: provider-azure-creds
  namespace: crossplane-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-store
    kind: ClusterSecretStore
  target:
    name: provider-azure-creds
    creationPolicy: Owner
  data:
    - secretKey: credentials
      remoteRef:
        key: crossplane/azure-sp-json
---
apiVersion: azure.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: provider-azure-creds
      key: credentials
