image:
  registry: ghcr.io
  repository: ts-monorepo-template/lib-chart
  digest: ''
secrets:
  backend: keyring
  refreshInterval: 1h
networkPolicy:
  defaultDeny: true
replicas: 1
autoscaling:
  enabled: false
podDisruptionBudget:
  enabled: false
monitoring:
  enabled: true
