image:
  registry: ghcr.io
  repository: ts-monorepo-template/rs-hello
replicas: 1
resources:
  requests:
    cpu: 25m
    memory: 16Mi
  limits:
    cpu: 250m
    memory: 96Mi
autoscaling:
  enabled: false
podDisruptionBudget:
  enabled: false
monitoring:
  enabled: true
