# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user/v1/user.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'user/v1/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user/v1/user.proto\x12\x07user.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x01\n\x04User\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n\x05\x65mail\x18\x02 \x01(\tR\x05\x65mail\x12!\n\x0c\x64isplay_name\x18\x03 \x01(\tR\x0b\x64isplayName\x12\x39\n\ncreated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tcreatedAt\" \n\x0eGetUserRequest\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\"L\n\x11\x43reateUserRequest\x12\x14\n\x05\x65mail\x18\x01 \x01(\tR\x05\x65mail\x12!\n\x0c\x64isplay_name\x18\x02 \x01(\tR\x0b\x64isplayName\"N\n\x10ListUsersRequest\x12\x1b\n\tpage_size\x18\x01 \x01(\x05R\x08pageSize\x12\x1d\n\npage_token\x18\x02 \x01(\tR\tpageToken\"`\n\x11ListUsersResponse\x12#\n\x05users\x18\x01 \x03(\x0b\x32\r.user.v1.UserR\x05users\x12&\n\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xbd\x01\n\x0bUserService\x12\x31\n\x07GetUser\x12\x17.user.v1.GetUserRequest\x1a\r.user.v1.User\x12\x37\n\nCreateUser\x12\x1a.user.v1.CreateUserRequest\x1a\r.user.v1.User\x12\x42\n\tListUsers\x12\x19.user.v1.ListUsersRequest\x1a\x1a.user.v1.ListUsersResponseB\x96\x01\n\x0b\x63om.user.v1B\tUserProtoP\x01Z?github.com/ts-monorepo-template/contracts/gen/go/user/v1;userv1\xa2\x02\x03UXX\xaa\x02\x07User.V1\xca\x02\x07User\\V1\xe2\x02\x13User\\V1\\GPBMetadata\xea\x02\x08User::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user.v1.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.user.v1B\tUserProtoP\001Z?github.com/ts-monorepo-template/contracts/gen/go/user/v1;userv1\242\002\003UXX\252\002\007User.V1\312\002\007User\\V1\342\002\023User\\V1\\GPBMetadata\352\002\010User::V1'
  _globals['_USER']._serialized_start=65
  _globals['_USER']._serialized_end=203
  _globals['_GETUSERREQUEST']._serialized_start=205
  _globals['_GETUSERREQUEST']._serialized_end=237
  _globals['_CREATEUSERREQUEST']._serialized_start=239
  _globals['_CREATEUSERREQUEST']._serialized_end=315
  _globals['_LISTUSERSREQUEST']._serialized_start=317
  _globals['_LISTUSERSREQUEST']._serialized_end=395
  _globals['_LISTUSERSRESPONSE']._serialized_start=397
  _globals['_LISTUSERSRESPONSE']._serialized_end=493
  _globals['_USERSERVICE']._serialized_start=496
  _globals['_USERSERVICE']._serialized_end=685
# @@protoc_insertion_point(module_scope)
