---
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml
driver:
  name: docker
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callbacks_enabled: profile_tasks
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
