apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - patch-and-transform.yaml
  - go-templating.yaml
  - environment-configs.yaml
  - auto-ready.yaml
  - extra-resources.yaml
  - kcl.yaml
