apiVersion: pn.cloud/v1alpha1
kind: RedisClusterClaim
metadata:
  name: go-hello
  namespace: prod
  labels:
    app.kubernetes.io/name: go-hello
    app.kubernetes.io/component: redis
spec:
  env: prod
  size: m
  tls: true
  persistence: true
  connectionSecret: go-hello-redis-conn
  compositionSelector:
    matchLabels:
      pn.cloud/variant: small
