apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - xpostgrescluster.yaml
  - xrediscluster.yaml
  - xrabbitmqcluster.yaml
  - xkafkacluster.yaml
  - xkafkatopic.yaml
  - xclickhousecluster.yaml
  - xopensearchcluster.yaml
  - xbucket.yaml
  - xsecretbinding.yaml
