apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xclickhouseclusters.pn.cloud
spec:
  group: pn.cloud
  names:
    kind: XClickHouseCluster
    plural: xclickhouseclusters
  claimNames:
    kind: ClickHouseClusterClaim
    plural: clickhouseclusterclaims
  defaultCompositionRef:
    name: xclickhousecluster-altinity-singlenode
  connectionSecretKeys: [host, port, native_port, username, password]
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [env]
              properties:
                env: { type: string, enum: [dev, staging, prod] }
                size: { type: string, enum: [xs, s, m, l], default: s }
                shards: { type: integer }
                replicas: { type: integer }
                keepers: { type: integer }
                version: { type: string, default: '24.8.4.13' }
                image:
                  { type: string, default: 'altinity/clickhouse-server:24.8.4.13.altinitystable' }
                storage:
                  type: object
                  properties:
                    class: { type: string }
                    size: { type: string }
                users:
                  type: array
                  items:
                    type: object
                    required: [name]
                    properties:
                      name: { type: string }
                      networks:
                        type: array
                        items: { type: string }
                      grants:
                        type: array
                        items: { type: string }
