apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xkafkatopics.pn.cloud
spec:
  group: pn.cloud
  names:
    kind: XKafkaTopic
    plural: xkafkatopics
  claimNames:
    kind: KafkaTopicClaim
    plural: kafkatopicclaims
  defaultCompositionRef:
    name: xkafkatopic-strimzi
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [env, cluster, partitions]
              properties:
                env: { type: string, enum: [dev, staging, prod] }
                cluster: { type: string }
                partitions: { type: integer }
                replicas: { type: integer, default: 3 }
                retentionMs: { type: integer }
                cleanupPolicy:
                  { type: string, enum: [delete, compact, 'compact,delete'], default: delete }
                config:
                  type: object
                  additionalProperties: { type: string }
