apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xredisclusters.pn.cloud
spec:
  group: pn.cloud
  names:
    kind: XRedisCluster
    plural: xredisclusters
  claimNames:
    kind: RedisClusterClaim
    plural: redisclusterclaims
  defaultCompositionRef:
    name: xrediscluster-kubeblocks-singlenode
  connectionSecretKeys: [host, port, password]
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [env]
              properties:
                env: { type: string, enum: [dev, staging, prod] }
                size: { type: string, enum: [xs, s, m, l], default: s }
                replicas: { type: integer }
                persistence:
                  type: object
                  properties:
                    enabled: { type: boolean, default: true }
                    storageGi: { type: integer }
                tls:
                  type: object
                  properties:
                    enabled: { type: boolean, default: false }
