apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xsecretbindings.pn.cloud
spec:
  group: pn.cloud
  names:
    kind: XSecretBinding
    plural: xsecretbindings
  claimNames:
    kind: SecretBindingClaim
    plural: secretbindingclaims
  defaultCompositionRef:
    name: xsecretbinding-eso
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [targetNamespace, sourceKey, name]
              properties:
                targetNamespace: { type: string }
                sourceKey: { type: string }
                name: { type: string }
                store: { type: string }
