apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - xregistryinstance.yaml
  - xschemagroup.yaml
  - xschemaartifact.yaml
  - xkafkaproxyplane.yaml
  - xvirtualkafkacluster.yaml
  - xkafkaprotocolfilter.yaml
  - xdatacontract.yaml
  - xglobalruleset.yaml
  - xrecordencryptionfilter.yaml
  - xrecordvalidationfilter.yaml
  - xauthorizationfilter.yaml
