apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - xregistryinstance-apicurio.yaml
  - xschemagroup-apicurio-http.yaml
  - xschemaartifact-apicurio-http.yaml
  - xkafkaproxyplane-kroxylicious.yaml
  - xvirtualkafkacluster-kroxylicious.yaml
  - xkafkaprotocolfilter-kroxylicious-kcl.yaml
  - xdatacontract-default.yaml
  - xglobalruleset-apicurio-http.yaml
  - xrecordencryptionfilter-kroxylicious.yaml
  - xrecordvalidationfilter-kroxylicious.yaml
  - xauthorizationfilter-kroxylicious.yaml
