apiVersion: pn.cloud/v1alpha1
kind: RedisClusterClaim
metadata:
  name: py-hello
  namespace: staging
  labels:
    app.kubernetes.io/name: py-hello
    app.kubernetes.io/component: redis
spec:
  env: staging
  size: s
  tls: true
  persistence: true
  connectionSecret: py-hello-redis-conn
  compositionSelector:
    matchLabels:
      pn.cloud/variant: small
