apiVersion: pn.cloud/v1alpha1
kind: KafkaTopicClaim
metadata:
  name: user-events-v1
  namespace: staging
  labels:
    app.kubernetes.io/component: kafka-topic
    pn.cloud/shared: 'true'
spec:
  env: staging
  cluster: shared
  topic: user.events.v1
  partitions: 3
  replicas: 2
  retentionMs: 259200000
  cleanupPolicy: delete
  config:
    min.insync.replicas: '2'
    compression.type: 'producer'
  compositionSelector:
    matchLabels:
      pn.cloud/variant: strimzi
