apiVersion: pn.cloud/v1alpha1
kind: KeycloakClientClaim
metadata:
  name: rs-hello
  namespace: dev
  labels:
    app.kubernetes.io/name: rs-hello
    app.kubernetes.io/component: identity
spec:
  env: dev
  realm: platform
  clientId: rs-hello-dev
  redirectUris:
    - http://rs-hello.localtest.me/callback
  scopes:
    - openid
    - profile
    - email
  groupMappers:
    - { group: dev-engineers, claim: groups }
  serviceAccount:
    enabled: false
    roles: []
  connectionSecret: rs-hello-oidc-conn
  compositionSelector:
    matchLabels:
      pn.cloud/variant: default
