//! contracts — Rust bindings generated by buf into ../contracts/gen/rs/src.
//! Spec: docs/superpowers/specs/2026-06-03-platform-foundation-design.md §12.2.

#![allow(clippy::all, dead_code)]

pub mod user {
    pub mod v1 {
        include!("../../contracts/gen/rs/src/user.v1.rs");
    }
}

pub mod health {
    pub mod v1 {
        include!("../../contracts/gen/rs/src/health.v1.rs");
    }
}
