# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: health/v1/health.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'health/v1/health.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16health/v1/health.proto\x12\thealth.v1\".\n\x12HealthCheckRequest\x12\x18\n\x07service\x18\x01 \x01(\tR\x07service\"\xc8\x01\n\x13HealthCheckResponse\x12\x44\n\x06status\x18\x01 \x01(\x0e\x32,.health.v1.HealthCheckResponse.ServingStatusR\x06status\"k\n\rServingStatus\x12\x1e\n\x1aSERVING_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n\x16SERVING_STATUS_SERVING\x10\x01\x12\x1e\n\x1aSERVING_STATUS_NOT_SERVING\x10\x02\x32U\n\x0bHealthCheck\x12\x46\n\x05\x43heck\x12\x1d.health.v1.HealthCheckRequest\x1a\x1e.health.v1.HealthCheckResponseB\xa6\x01\n\rcom.health.v1B\x0bHealthProtoP\x01ZCgithub.com/ts-monorepo-template/contracts/gen/go/health/v1;healthv1\xa2\x02\x03HXX\xaa\x02\tHealth.V1\xca\x02\tHealth\\V1\xe2\x02\x15Health\\V1\\GPBMetadata\xea\x02\nHealth::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'health.v1.health_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\rcom.health.v1B\013HealthProtoP\001ZCgithub.com/ts-monorepo-template/contracts/gen/go/health/v1;healthv1\242\002\003HXX\252\002\tHealth.V1\312\002\tHealth\\V1\342\002\025Health\\V1\\GPBMetadata\352\002\nHealth::V1'
  _globals['_HEALTHCHECKREQUEST']._serialized_start=37
  _globals['_HEALTHCHECKREQUEST']._serialized_end=83
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=86
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=286
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_start=179
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_end=286
  _globals['_HEALTHCHECK']._serialized_start=288
  _globals['_HEALTHCHECK']._serialized_end=373
# @@protoc_insertion_point(module_scope)
