apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xrediscluster-kubeblocks-singlenode
  labels:
    pn.cloud/bundle: core
    pn.cloud/variant: singlenode
spec:
  compositeTypeRef:
    apiVersion: pn.cloud/v1alpha1
    kind: XRedisCluster
  mode: Pipeline
  pipeline:
    - step: load-env
      functionRef: { name: function-environment-configs }
      input:
        apiVersion: environmentconfigs.fn.crossplane.io/v1beta1
        kind: Input
        spec:
          environmentConfigs:
            - type: Reference
              ref: { name: env-dev }
            - type: Reference
              ref: { name: env-staging }
            - type: Reference
              ref: { name: env-prod }
    - step: render
      functionRef: { name: function-go-templating }
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            apiVersion: apps.kubeblocks.io/v1alpha1
            kind: Cluster
            metadata:
              name: {{ .observed.composite.resource.metadata.name }}
              namespace: {{ index .observed.composite.resource.spec "claimRef" "namespace" | default "default" }}
            spec:
              clusterDefinitionRef: redis
              componentSpecs:
                - name: redis
                  componentDefRef: redis
                  replicas: 1
    - step: patch
      functionRef: { name: function-patch-and-transform }
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources: []
    - step: ready
      functionRef: { name: function-auto-ready }
